In [1]:
import os
import numpy as np

In [12]:
# directories
model_type = 'cmip6'

if model_type=='cmip6':
    data_dir = "/Users/sethbushinsky/UHM_Ocean_BGC_Group Dropbox/Datasets/Model_Output/CMIP6/"
    run_type = {'historical_download/', 'ssp585_download/'}
else:
    # data_dir = "/Users/smb-uh/UHM_Ocean_BGC_Group Dropbox/Datasets/Model_Output/CMIP5/"
    data_dir = "/Users/sethbushinsky/UHM_Ocean_BGC_Group Dropbox/Datasets/Model_Output/CMIP5/"
    run_type = {'None'}
    
test_dir_all = {'dissic/monthly/', 'talk/monthly/', 'fgco2/', 'intpp/', 'mlotst/', 'so/', 'sos/', 'spco2/', 'thetao/', 'tos/'}

In [21]:
for test_dir in sorted(test_dir_all):
    for run in run_type:
        if run=='None':
            dir_mod = ''
        else:
            dir_mod = run
        
        # read in original_files
        file_list = []

        for file in os.listdir(data_dir + test_dir + dir_mod + 'original_files'):
            if file.endswith('.nc'):
                file_list.append(file)
        # print(file_list)
        # print(len(file_list))
        # check list of original files against list of regridded files

        regrid_list = []

        for file in os.listdir(data_dir + test_dir + 'regrid/' + dir_mod):
            if file.endswith('.nc'):
                regrid_list.append(file)

        # print(regrid_list)
        # print(len(regrid_list))

        original_in_regrid = np.zeros(len(file_list))
        regrid_matched = np.zeros(len(regrid_list))

        for idx, file in enumerate(file_list):
            if file in regrid_list:
                original_in_regrid[idx] = 1

                regrid_index = regrid_list.index(file)
                regrid_matched[regrid_index] = 1

        print(' ')
        print(test_dir + dir_mod)

        print(original_in_regrid)
        print(regrid_matched)

        print('original files not present in regrid files')
        for idx, file in enumerate(file_list): 
            if (original_in_regrid[idx]==0): print(file)

        print(' ')

        print('regrid files not present in original files')
        for idx, file in enumerate(regrid_list): 
            if (regrid_matched[idx]==0): print(file)

        print(' ')


 
dissic/monthly/historical_download/
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
original files not present in regrid files
 
regrid files not present in original files
 
 
dissic/monthly/ssp585_download/
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
original files not present in regrid files
 
regrid files not present in original files
 
 
fgco2/historical_download/
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
original files not present in regrid files
 
regrid files not present in original files
 
 
fgco2/ssp585_download/
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
original files not present in regrid files
 
regrid files not present in origi